# -*- coding: utf-8 -*-
"""2_hr_attrition_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pcrTQb69kFwISwax89zsEiTQYpvVKH6p
"""

"""Project 2: HR Analytics & Attrition (dataset: IBM HR Analytics Employee Attrition CSV from Kaggle)"""
import os
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

os.makedirs("outputs", exist_ok=True)
DB_URL = os.getenv("DB_URL", "sqlite:///portfolio.db")

df = pd.read_csv("data/WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.columns = [c.strip().lower() for c in df.columns]
df = df.drop_duplicates()
df["left_company"] = (df["attrition"] == "Yes").astype(int)
print("Employees:", len(df), "| Overall attrition:", f"{df['left_company'].mean():.1%}")

# Attrition by department / overtime / experience band
dept = (df.groupby("department")["left_company"].mean() * 100).round(1).sort_values(ascending=False)
print(dept)
ot = (df.groupby("overtime")["left_company"].mean() * 100).round(1)
df["tenure_band"] = pd.cut(df["yearsatcompany"], [-1, 2, 5, 10, 50], labels=["0-2", "3-5", "6-10", "10+"])
tenure = (df.groupby("tenure_band", observed=True)["left_company"].mean() * 100).round(1)

dept.plot(kind="bar", color="#C55A11", title="Attrition % by Department")
plt.ylabel("%"); plt.tight_layout(); plt.savefig("outputs/attrition_by_department.png", dpi=150); plt.clf()
ot.plot(kind="bar", color="#7030A0", title="Attrition % by Overtime")
plt.tight_layout(); plt.savefig("outputs/attrition_by_overtime.png", dpi=150); plt.clf()
tenure.plot(kind="bar", color="#2E75B6", title="Attrition % by Years at Company")
plt.tight_layout(); plt.savefig("outputs/attrition_by_tenure.png", dpi=150); plt.clf()
df.boxplot(column="monthlyincome", by="attrition")
plt.title("Monthly Income vs Attrition"); plt.suptitle("")
plt.tight_layout(); plt.savefig("outputs/income_vs_attrition.png", dpi=150); plt.clf()

df.drop(columns=["tenure_band"]).to_sql("hr_employees", create_engine(DB_URL), if_exists="replace", index=False)
print("Done. Table 'hr_employees' loaded.")