# -*- coding: utf-8 -*-
"""2_hr_queries.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jbon2YehjyHZlqUPY7WCyGWH_30PZSqq
"""

-- Project 2: HR Attrition (table: hr_employees). left_company: 1 = left, 0 = stayed.

-- 1. Overall attrition rate
SELECT COUNT(*) AS employees, SUM(left_company) AS left_count,
       ROUND(AVG(left_company)*100,1) AS attrition_pct FROM hr_employees;

-- 2. Attrition, salary and tenure by department
SELECT department, COUNT(*) AS employees,
       ROUND(AVG(left_company)*100,1) AS attrition_pct,
       ROUND(AVG(monthlyincome),0) AS avg_income,
       ROUND(AVG(yearsatcompany),1) AS avg_tenure
FROM hr_employees GROUP BY department ORDER BY attrition_pct DESC;

-- 3. Attrition by job role
SELECT jobrole, ROUND(AVG(left_company)*100,1) AS attrition_pct
FROM hr_employees GROUP BY jobrole ORDER BY attrition_pct DESC;

-- 4. Overtime impact
SELECT overtime, ROUND(AVG(left_company)*100,1) AS attrition_pct
FROM hr_employees GROUP BY overtime;

-- 5. Leavers vs stayers: income and tenure
SELECT attrition, ROUND(AVG(monthlyincome),0) AS avg_income, ROUND(AVG(yearsatcompany),1) AS avg_years
FROM hr_employees GROUP BY attrition;

-- 6. Departments above the company average (subquery)
SELECT department, ROUND(AVG(left_company)*100,1) AS attrition_pct
FROM hr_employees GROUP BY department
HAVING AVG(left_company) > (SELECT AVG(left_company) FROM hr_employees);